// Generated by svd2swift.

import MMIO

/// General Purpose Input/Output
public let gpio = GPIO(unsafeAddress: 0x60091000)

/// SPI (Serial Peripheral Interface) Controller 0
public let spi0 = SPI0(unsafeAddress: 0x60002000)

/// UART (Universal Asynchronous Receiver-Transmitter) Controller 0
public let uart0 = UART0(unsafeAddress: 0x60000000)
