// Generated by svd2swift.

import MMIO

/// MODEM_SYSCON Peripheral
@RegisterBlock
public struct MODEM_SYSCON {
    /// TEST_CONF
    @RegisterBlock(offset: 0x0)
    public var test_conf: Register<TEST_CONF>

    /// CLK_CONF
    @RegisterBlock(offset: 0x4)
    public var clk_conf: Register<CLK_CONF>

    /// CLK_CONF_FORCE_ON
    @RegisterBlock(offset: 0x8)
    public var clk_conf_force_on: Register<CLK_CONF_FORCE_ON>

    /// CLK_CONF_POWER_ST
    @RegisterBlock(offset: 0xc)
    public var clk_conf_power_st: Register<CLK_CONF_POWER_ST>

    /// MODEM_RST_CONF
    @RegisterBlock(offset: 0x10)
    public var modem_rst_conf: Register<MODEM_RST_CONF>

    /// CLK_CONF1
    @RegisterBlock(offset: 0x14)
    public var clk_conf1: Register<CLK_CONF1>

    /// CLK_CONF1_FORCE_ON
    @RegisterBlock(offset: 0x18)
    public var clk_conf1_force_on: Register<CLK_CONF1_FORCE_ON>

    /// WIFI_BB_CFG
    @RegisterBlock(offset: 0x1c)
    public var wifi_bb_cfg: Register<WIFI_BB_CFG>

    /// MEM_CONF
    @RegisterBlock(offset: 0x20)
    public var mem_conf: Register<MEM_CONF>

    /// DATE
    @RegisterBlock(offset: 0x24)
    public var date: Register<DATE>
}

extension MODEM_SYSCON {
    /// TEST_CONF
    @Register(bitWidth: 32)
    public struct TEST_CONF {
        /// CLK_EN
        @ReadWrite(bits: 0..<1)
        public var clk_en: CLK_EN
    }

    /// CLK_CONF
    @Register(bitWidth: 32)
    public struct CLK_CONF {
        /// CLK_DATA_DUMP_MUX
        @ReadWrite(bits: 21..<22)
        public var clk_data_dump_mux: CLK_DATA_DUMP_MUX

        /// CLK_ETM_EN
        @ReadWrite(bits: 22..<23)
        public var clk_etm_en: CLK_ETM_EN

        /// CLK_ZB_APB_EN
        @ReadWrite(bits: 23..<24)
        public var clk_zb_apb_en: CLK_ZB_APB_EN

        /// CLK_ZB_MAC_EN
        @ReadWrite(bits: 24..<25)
        public var clk_zb_mac_en: CLK_ZB_MAC_EN

        /// CLK_MODEM_SEC_ECB_EN
        @ReadWrite(bits: 25..<26)
        public var clk_modem_sec_ecb_en: CLK_MODEM_SEC_ECB_EN

        /// CLK_MODEM_SEC_CCM_EN
        @ReadWrite(bits: 26..<27)
        public var clk_modem_sec_ccm_en: CLK_MODEM_SEC_CCM_EN

        /// CLK_MODEM_SEC_BAH_EN
        @ReadWrite(bits: 27..<28)
        public var clk_modem_sec_bah_en: CLK_MODEM_SEC_BAH_EN

        /// CLK_MODEM_SEC_APB_EN
        @ReadWrite(bits: 28..<29)
        public var clk_modem_sec_apb_en: CLK_MODEM_SEC_APB_EN

        /// CLK_MODEM_SEC_EN
        @ReadWrite(bits: 29..<30)
        public var clk_modem_sec_en: CLK_MODEM_SEC_EN

        /// CLK_BLE_TIMER_EN
        @ReadWrite(bits: 30..<31)
        public var clk_ble_timer_en: CLK_BLE_TIMER_EN

        /// CLK_DATA_DUMP_EN
        @ReadWrite(bits: 31..<32)
        public var clk_data_dump_en: CLK_DATA_DUMP_EN
    }

    /// CLK_CONF_FORCE_ON
    @Register(bitWidth: 32)
    public struct CLK_CONF_FORCE_ON {
        /// CLK_ETM_FO
        @ReadWrite(bits: 22..<23)
        public var clk_etm_fo: CLK_ETM_FO

        /// CLK_ZB_APB_FO
        @ReadWrite(bits: 23..<24)
        public var clk_zb_apb_fo: CLK_ZB_APB_FO

        /// CLK_ZB_MAC_FO
        @ReadWrite(bits: 24..<25)
        public var clk_zb_mac_fo: CLK_ZB_MAC_FO

        /// CLK_MODEM_SEC_ECB_FO
        @ReadWrite(bits: 25..<26)
        public var clk_modem_sec_ecb_fo: CLK_MODEM_SEC_ECB_FO

        /// CLK_MODEM_SEC_CCM_FO
        @ReadWrite(bits: 26..<27)
        public var clk_modem_sec_ccm_fo: CLK_MODEM_SEC_CCM_FO

        /// CLK_MODEM_SEC_BAH_FO
        @ReadWrite(bits: 27..<28)
        public var clk_modem_sec_bah_fo: CLK_MODEM_SEC_BAH_FO

        /// CLK_MODEM_SEC_APB_FO
        @ReadWrite(bits: 28..<29)
        public var clk_modem_sec_apb_fo: CLK_MODEM_SEC_APB_FO

        /// CLK_MODEM_SEC_FO
        @ReadWrite(bits: 29..<30)
        public var clk_modem_sec_fo: CLK_MODEM_SEC_FO

        /// CLK_BLE_TIMER_FO
        @ReadWrite(bits: 30..<31)
        public var clk_ble_timer_fo: CLK_BLE_TIMER_FO

        /// CLK_DATA_DUMP_FO
        @ReadWrite(bits: 31..<32)
        public var clk_data_dump_fo: CLK_DATA_DUMP_FO
    }

    /// CLK_CONF_POWER_ST
    @Register(bitWidth: 32)
    public struct CLK_CONF_POWER_ST {
        /// CLK_ZB_ST_MAP
        @ReadWrite(bits: 8..<12)
        public var clk_zb_st_map: CLK_ZB_ST_MAP

        /// CLK_FE_ST_MAP
        @ReadWrite(bits: 12..<16)
        public var clk_fe_st_map: CLK_FE_ST_MAP

        /// CLK_BT_ST_MAP
        @ReadWrite(bits: 16..<20)
        public var clk_bt_st_map: CLK_BT_ST_MAP

        /// CLK_WIFI_ST_MAP
        @ReadWrite(bits: 20..<24)
        public var clk_wifi_st_map: CLK_WIFI_ST_MAP

        /// CLK_MODEM_PERI_ST_MAP
        @ReadWrite(bits: 24..<28)
        public var clk_modem_peri_st_map: CLK_MODEM_PERI_ST_MAP

        /// CLK_MODEM_APB_ST_MAP
        @ReadWrite(bits: 28..<32)
        public var clk_modem_apb_st_map: CLK_MODEM_APB_ST_MAP
    }

    /// MODEM_RST_CONF
    @Register(bitWidth: 32)
    public struct MODEM_RST_CONF {
        /// RST_WIFIBB
        @ReadWrite(bits: 8..<9)
        public var rst_wifibb: RST_WIFIBB

        /// RST_WIFIMAC
        @ReadWrite(bits: 10..<11)
        public var rst_wifimac: RST_WIFIMAC

        /// RST_FE
        @ReadWrite(bits: 14..<15)
        public var rst_fe: RST_FE

        /// RST_BTMAC_APB
        @ReadWrite(bits: 15..<16)
        public var rst_btmac_apb: RST_BTMAC_APB

        /// RST_BTMAC
        @ReadWrite(bits: 16..<17)
        public var rst_btmac: RST_BTMAC

        /// RST_BTBB_APB
        @ReadWrite(bits: 17..<18)
        public var rst_btbb_apb: RST_BTBB_APB

        /// RST_BTBB
        @ReadWrite(bits: 18..<19)
        public var rst_btbb: RST_BTBB

        /// RST_ETM
        @ReadWrite(bits: 22..<23)
        public var rst_etm: RST_ETM

        /// RST_ZBMAC
        @ReadWrite(bits: 24..<25)
        public var rst_zbmac: RST_ZBMAC

        /// RST_MODEM_ECB
        @ReadWrite(bits: 25..<26)
        public var rst_modem_ecb: RST_MODEM_ECB

        /// RST_MODEM_CCM
        @ReadWrite(bits: 26..<27)
        public var rst_modem_ccm: RST_MODEM_CCM

        /// RST_MODEM_BAH
        @ReadWrite(bits: 27..<28)
        public var rst_modem_bah: RST_MODEM_BAH

        /// RST_MODEM_SEC
        @ReadWrite(bits: 29..<30)
        public var rst_modem_sec: RST_MODEM_SEC

        /// RST_BLE_TIMER
        @ReadWrite(bits: 30..<31)
        public var rst_ble_timer: RST_BLE_TIMER

        /// RST_DATA_DUMP
        @ReadWrite(bits: 31..<32)
        public var rst_data_dump: RST_DATA_DUMP
    }

    /// CLK_CONF1
    @Register(bitWidth: 32)
    public struct CLK_CONF1 {
        /// CLK_WIFIBB_22M_EN
        @ReadWrite(bits: 0..<1)
        public var clk_wifibb_22m_en: CLK_WIFIBB_22M_EN

        /// CLK_WIFIBB_40M_EN
        @ReadWrite(bits: 1..<2)
        public var clk_wifibb_40m_en: CLK_WIFIBB_40M_EN

        /// CLK_WIFIBB_44M_EN
        @ReadWrite(bits: 2..<3)
        public var clk_wifibb_44m_en: CLK_WIFIBB_44M_EN

        /// CLK_WIFIBB_80M_EN
        @ReadWrite(bits: 3..<4)
        public var clk_wifibb_80m_en: CLK_WIFIBB_80M_EN

        /// CLK_WIFIBB_40X_EN
        @ReadWrite(bits: 4..<5)
        public var clk_wifibb_40x_en: CLK_WIFIBB_40X_EN

        /// CLK_WIFIBB_80X_EN
        @ReadWrite(bits: 5..<6)
        public var clk_wifibb_80x_en: CLK_WIFIBB_80X_EN

        /// CLK_WIFIBB_40X1_EN
        @ReadWrite(bits: 6..<7)
        public var clk_wifibb_40x1_en: CLK_WIFIBB_40X1_EN

        /// CLK_WIFIBB_80X1_EN
        @ReadWrite(bits: 7..<8)
        public var clk_wifibb_80x1_en: CLK_WIFIBB_80X1_EN

        /// CLK_WIFIBB_160X1_EN
        @ReadWrite(bits: 8..<9)
        public var clk_wifibb_160x1_en: CLK_WIFIBB_160X1_EN

        /// CLK_WIFIMAC_EN
        @ReadWrite(bits: 9..<10)
        public var clk_wifimac_en: CLK_WIFIMAC_EN

        /// CLK_WIFI_APB_EN
        @ReadWrite(bits: 10..<11)
        public var clk_wifi_apb_en: CLK_WIFI_APB_EN

        /// CLK_FE_20M_EN
        @ReadWrite(bits: 11..<12)
        public var clk_fe_20m_en: CLK_FE_20M_EN

        /// CLK_FE_40M_EN
        @ReadWrite(bits: 12..<13)
        public var clk_fe_40m_en: CLK_FE_40M_EN

        /// CLK_FE_80M_EN
        @ReadWrite(bits: 13..<14)
        public var clk_fe_80m_en: CLK_FE_80M_EN

        /// CLK_FE_160M_EN
        @ReadWrite(bits: 14..<15)
        public var clk_fe_160m_en: CLK_FE_160M_EN

        /// CLK_FE_CAL_160M_EN
        @ReadWrite(bits: 15..<16)
        public var clk_fe_cal_160m_en: CLK_FE_CAL_160M_EN

        /// CLK_FE_APB_EN
        @ReadWrite(bits: 16..<17)
        public var clk_fe_apb_en: CLK_FE_APB_EN

        /// CLK_BT_APB_EN
        @ReadWrite(bits: 17..<18)
        public var clk_bt_apb_en: CLK_BT_APB_EN

        /// CLK_BT_EN
        @ReadWrite(bits: 18..<19)
        public var clk_bt_en: CLK_BT_EN

        /// CLK_WIFIBB_480M_EN
        @ReadWrite(bits: 19..<20)
        public var clk_wifibb_480m_en: CLK_WIFIBB_480M_EN

        /// CLK_FE_480M_EN
        @ReadWrite(bits: 20..<21)
        public var clk_fe_480m_en: CLK_FE_480M_EN

        /// CLK_FE_ANAMODE_40M_EN
        @ReadWrite(bits: 21..<22)
        public var clk_fe_anamode_40m_en: CLK_FE_ANAMODE_40M_EN

        /// CLK_FE_ANAMODE_80M_EN
        @ReadWrite(bits: 22..<23)
        public var clk_fe_anamode_80m_en: CLK_FE_ANAMODE_80M_EN

        /// CLK_FE_ANAMODE_160M_EN
        @ReadWrite(bits: 23..<24)
        public var clk_fe_anamode_160m_en: CLK_FE_ANAMODE_160M_EN
    }

    /// CLK_CONF1_FORCE_ON
    @Register(bitWidth: 32)
    public struct CLK_CONF1_FORCE_ON {
        /// CLK_WIFIBB_22M_FO
        @ReadWrite(bits: 0..<1)
        public var clk_wifibb_22m_fo: CLK_WIFIBB_22M_FO

        /// CLK_WIFIBB_40M_FO
        @ReadWrite(bits: 1..<2)
        public var clk_wifibb_40m_fo: CLK_WIFIBB_40M_FO

        /// CLK_WIFIBB_44M_FO
        @ReadWrite(bits: 2..<3)
        public var clk_wifibb_44m_fo: CLK_WIFIBB_44M_FO

        /// CLK_WIFIBB_80M_FO
        @ReadWrite(bits: 3..<4)
        public var clk_wifibb_80m_fo: CLK_WIFIBB_80M_FO

        /// CLK_WIFIBB_40X_FO
        @ReadWrite(bits: 4..<5)
        public var clk_wifibb_40x_fo: CLK_WIFIBB_40X_FO

        /// CLK_WIFIBB_80X_FO
        @ReadWrite(bits: 5..<6)
        public var clk_wifibb_80x_fo: CLK_WIFIBB_80X_FO

        /// CLK_WIFIBB_40X1_FO
        @ReadWrite(bits: 6..<7)
        public var clk_wifibb_40x1_fo: CLK_WIFIBB_40X1_FO

        /// CLK_WIFIBB_80X1_FO
        @ReadWrite(bits: 7..<8)
        public var clk_wifibb_80x1_fo: CLK_WIFIBB_80X1_FO

        /// CLK_WIFIBB_160X1_FO
        @ReadWrite(bits: 8..<9)
        public var clk_wifibb_160x1_fo: CLK_WIFIBB_160X1_FO

        /// CLK_WIFIMAC_FO
        @ReadWrite(bits: 9..<10)
        public var clk_wifimac_fo: CLK_WIFIMAC_FO

        /// CLK_WIFI_APB_FO
        @ReadWrite(bits: 10..<11)
        public var clk_wifi_apb_fo: CLK_WIFI_APB_FO

        /// CLK_FE_20M_FO
        @ReadWrite(bits: 11..<12)
        public var clk_fe_20m_fo: CLK_FE_20M_FO

        /// CLK_FE_40M_FO
        @ReadWrite(bits: 12..<13)
        public var clk_fe_40m_fo: CLK_FE_40M_FO

        /// CLK_FE_80M_FO
        @ReadWrite(bits: 13..<14)
        public var clk_fe_80m_fo: CLK_FE_80M_FO

        /// CLK_FE_160M_FO
        @ReadWrite(bits: 14..<15)
        public var clk_fe_160m_fo: CLK_FE_160M_FO

        /// CLK_FE_CAL_160M_FO
        @ReadWrite(bits: 15..<16)
        public var clk_fe_cal_160m_fo: CLK_FE_CAL_160M_FO

        /// CLK_FE_APB_FO
        @ReadWrite(bits: 16..<17)
        public var clk_fe_apb_fo: CLK_FE_APB_FO

        /// CLK_BT_APB_FO
        @ReadWrite(bits: 17..<18)
        public var clk_bt_apb_fo: CLK_BT_APB_FO

        /// CLK_BT_FO
        @ReadWrite(bits: 18..<19)
        public var clk_bt_fo: CLK_BT_FO

        /// CLK_WIFIBB_480M_FO
        @ReadWrite(bits: 19..<20)
        public var clk_wifibb_480m_fo: CLK_WIFIBB_480M_FO

        /// CLK_FE_480M_FO
        @ReadWrite(bits: 20..<21)
        public var clk_fe_480m_fo: CLK_FE_480M_FO

        /// CLK_FE_ANAMODE_40M_FO
        @ReadWrite(bits: 21..<22)
        public var clk_fe_anamode_40m_fo: CLK_FE_ANAMODE_40M_FO

        /// CLK_FE_ANAMODE_80M_FO
        @ReadWrite(bits: 22..<23)
        public var clk_fe_anamode_80m_fo: CLK_FE_ANAMODE_80M_FO

        /// CLK_FE_ANAMODE_160M_FO
        @ReadWrite(bits: 23..<24)
        public var clk_fe_anamode_160m_fo: CLK_FE_ANAMODE_160M_FO
    }

    /// WIFI_BB_CFG
    @Register(bitWidth: 32)
    public struct WIFI_BB_CFG {
        /// WIFI_BB_CFG_FIELD
        @ReadWrite(bits: 0..<32)
        public var wifi_bb_cfg_field: WIFI_BB_CFG_FIELD
    }

    /// MEM_CONF
    @Register(bitWidth: 32)
    public struct MEM_CONF {
        /// MODEM_MEM_WP
        @ReadWrite(bits: 0..<3)
        public var modem_mem_wp: MODEM_MEM_WP

        /// MODEM_MEM_WA
        @ReadWrite(bits: 3..<6)
        public var modem_mem_wa: MODEM_MEM_WA

        /// MODEM_MEM_RA
        @ReadWrite(bits: 6..<8)
        public var modem_mem_ra: MODEM_MEM_RA
    }

    /// DATE
    @Register(bitWidth: 32)
    public struct DATE {
        /// DATE_FIELD
        @ReadWrite(bits: 0..<28)
        public var date_field: DATE_FIELD
    }
}
